import { BadRequestException, ConflictException, Injectable } from '@nestjs/common';
import { AddWaitlistDto } from './dto/add-waitlist.dto';
import { ListWaitlistDto } from './dto/list-waitlist.dto';
import {
  AddWaitlistResponseEntity,
  WaitlistListResponseEntity,
} from './profile.entity';
import { ProfileRepository } from './profile.repository';

/**
 * Pulls the Postgres `SQLSTATE` code out of an unknown thrown value.
 *
 * Drizzle wraps driver failures in `DrizzleQueryError` and puts the real
 * `PostgresError` (which carries `code`) on `cause`, so checking only the
 * top-level object misses it and every constraint violation degrades to a
 * 500. We walk a short cause chain to stay robust across driver versions
 * that throw the raw error instead.
 */
function extractPgErrorCode(error: unknown): string | undefined {
  let current = error;

  for (let depth = 0; depth < 5 && current !== null && current !== undefined; depth++) {
    if (
      typeof current === 'object' &&
      'code' in current &&
      typeof (current as { code?: unknown }).code === 'string'
    ) {
      return (current as { code: string }).code;
    }

    current =
      typeof current === 'object' && 'cause' in current
        ? (current as { cause?: unknown }).cause
        : undefined;
  }

  return undefined;
}

/**
 * Business-logic layer for profile / waiting-list concerns.
 *
 * Today this is a thin orchestrator over the repository. It is the
 * intentional home for things that are NOT data access:
 *   - access-control rules (e.g. admin-only visibility of emails)
 *   - response shaping / PII masking
 *   - cross-aggregate composition (e.g. join with users)
 *   - cache layers, instrumentation, side-effects
 *
 * The controller talks to this layer; this layer talks to the repository.
 */
@Injectable()
export class ProfileService {
  constructor(private readonly profileRepository: ProfileRepository) {}

  /**
   * List waiting-list entries using the validated body DTO.
   * Translates the DTO → repository options, then wraps the rows in a
   * success envelope so clients get a message alongside the data.
   * No persistence concerns here.
   */
  async listWaitlist(dto: ListWaitlistDto): Promise<WaitlistListResponseEntity> {
    const rows = await this.profileRepository.findWaitlist({
      email: dto.email,
      userId: dto.userId,
      platform: dto.platform,
      // Default to active-only even if the DTO default was bypassed.
      isActive: dto.isActive ?? true,
      limit: dto.limit,
      offset: dto.offset,
    });

    return {
      success: true,
      message: rows.length
        ? `${rows.length} waiting-list ${rows.length === 1 ? 'entry' : 'entries'} found.`
        : 'No waiting-list entries matched these filters.',
      count: rows.length,
      data: rows,
    };
  }

  /**
   * Adds one sign-up to the waiting list.
   *
   * Email is lower-cased on the way in so it matches the `lower()`
   * comparison `listWaitlist` uses. `id` is generated by the database and
   * `user_id` is intentionally not accepted from the client. Driver-level
   * constraint failures are translated to HTTP semantics here: duplicate
   * email → 409.
   */
  async addToWaitlist(
    dto: AddWaitlistDto,
  ): Promise<AddWaitlistResponseEntity> {
    try {
      const row = await this.profileRepository.insertWaitlist({
        email: dto.email.toLowerCase(),
        ...(dto.platform !== undefined ? { platform: dto.platform } : {}),
      });

      return {
        success: true,
        message: 'Added to waiting list successfully.',
        data: row,
      };
    } catch (error: unknown) {
      const code = extractPgErrorCode(error);

      if (code === '23505') {
        throw new ConflictException('This email is already on the waiting list.');
      }

      if (code === '23503') {
        throw new BadRequestException(
          'The userId does not reference an existing profile.',
        );
      }

      throw error;
    }
  }
}
